# Generated by Django 4.1.2 on 2022-10-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, max_length=15, null=True)),
                ('reason', models.IntegerField(choices=[(0, 'Support'), (1, 'Bug Report'), (2, 'Feedback'), (3, 'Compliement'), (4, 'Complaint')])),
                ('content', models.TextField(max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'NEW'), (1, 'OPENED'), (2, 'IN PROGRESS'), (3, 'COMPLETE')], default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
