# Generated by Django 4.1.2 on 2022-10-07 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "reason",
                    models.IntegerField(
                        choices=[
                            (0, "Support"),
                            (1, "Bug Report"),
                            (2, "Feedback"),
                            (3, "Compliement"),
                            (4, "Complaint"),
                        ]
                    ),
                ),
                ("content", models.TextField(max_length=512)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "NEW"),
                            (1, "OPENED"),
                            (2, "IN PROGRESS"),
                            (3, "COMPLETE"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
